import { ITeam } from '../interfaces/team.interface';

export const Teams: ITeam[] = [
    {
        id: 0,
        leagueId: 0,
        title: 'AC Milan',
        logo: 'https://www.eredmenyek.com/res/image/data/htYjIjFa-bDzxUgK1.png',
    },
    {
        id: 1,
        leagueId: 0,
        title: 'AS Roma',
        logo: 'https://www.eredmenyek.com/res/image/data/Op2545Da-rawUVFkk.png',
    },
    {
        id: 2,
        leagueId: 0,
        title: 'Atalanta',
        logo: 'https://www.eredmenyek.com/res/image/data/xASUZ6il-S82PeYBB.png',
    },
    {
        id: 3,
        leagueId: 0,
        title: 'Bologna',
        logo: 'https://www.eredmenyek.com/res/image/data/j3Tyh1GG-bucnXust.png',
    },
    {
        id: 4,
        leagueId: 0,
        title: 'Cagliari',
        logo: 'https://www.eredmenyek.com/res/image/data/IBlLf9f5-fJEtvjYe.png',
    },
    {
        id: 5,
        leagueId: 0,
        title: 'Chievo',
        logo: 'https://www.eredmenyek.com/res/image/data/vwZUTcyB-MDbygWeU.png',
    },
    {
        id: 6,
        leagueId: 0,
        title: 'Empoli',
        logo: 'https://www.eredmenyek.com/res/image/data/h6XeO4e5-QeS1qfqn.png',
    },
    {
        id: 7,
        leagueId: 0,
        title: 'Fiorentina',
        logo: 'https://www.eredmenyek.com/res/image/data/Mk94AUkl-x4ZuTDZ7.png',
    },
    {
        id: 8,
        leagueId: 0,
        title: 'Frosinone',
        logo: 'https://www.eredmenyek.com/res/image/data/MP0Dgnhl-jXzYs3WB.png',
    },
    {
        id: 9,
        leagueId: 0,
        title: 'Genoa',
        logo: 'https://www.eredmenyek.com/res/image/data/KKFT9LZA-ERLRjHRE.png',
    },
    {
        id: 10,
        leagueId: 0,
        title: 'Inter',
        logo: 'https://www.eredmenyek.com/res/image/data/888s5CCa-0IrgnKLD.png',
    },
    {
        id: 11,
        leagueId: 0,
        title: 'Juventus',
        logo: 'https://www.eredmenyek.com/res/image/data/MybdvNGG-ja9Wx4TE.png',
    },
    {
        id: 12,
        leagueId: 0,
        title: 'Lazio',
        logo: 'https://www.eredmenyek.com/res/image/data/zXqymff5-67BxS1ca.png',
    },
    {
        id: 13,
        leagueId: 0,
        title: 'Napoli',
        logo: 'https://www.eredmenyek.com/res/image/data/lhPsgJWg-zyNNicC8.png',
    },
    {
        id: 14,
        leagueId: 0,
        title: 'Parma',
        logo: 'https://www.eredmenyek.com/res/image/data/YcrE7ae5-G8Rtggfp.png',
    },
    {
        id: 15,
        leagueId: 0,
        title: 'Sampdoria',
        logo: 'https://www.eredmenyek.com/res/image/data/UuEViRAr-v36hOJdO.png',
    },
    {
        id: 16,
        leagueId: 0,
        title: 'Sassuolo',
        logo: 'https://www.eredmenyek.com/res/image/data/IFKEHRGG-hWBv29Yp.png',
    },
    {
        id: 17,
        leagueId: 0,
        title: 'Spal',
        logo: 'https://www.eredmenyek.com/res/image/data/21y70myS-G8uIooXn.png',
    },
    {
        id: 18,
        leagueId: 0,
        title: 'Torino',
        logo: 'https://www.eredmenyek.com/res/image/data/OQWGjGcM-j3aMQhBo.png',
    },
    {
        id: 19,
        leagueId: 0,
        title: 'Udinese',
        logo: 'https://www.eredmenyek.com/res/image/data/AZBQMaYA-4bBXPzzK.png',
    },
    {
        id: 20,
        leagueId: 1,
        title: 'Arsenal',
        logo: 'https://www.eredmenyek.com/res/image/data/pfchdCg5-pU2IsJm8.png',
    },
    {
        id: 21,
        leagueId: 1,
        title: 'Bournemouth',
        logo: 'https://www.eredmenyek.com/res/image/data/2Pb55xWg-xtDkL8U0.png',
    },
    {
        id: 22,
        leagueId: 1,
        title: 'Brighton',
        logo: 'https://www.eredmenyek.com/res/image/data/40juIezB-IccPlIAs.png',
    },
    {
        id: 23,
        leagueId: 1,
        title: 'Burnley',
        logo: 'https://www.eredmenyek.com/res/image/data/lrUqOmDa-CKCXmfAs.png',
    },
    {
        id: 24,
        leagueId: 1,
        title: 'Cardiff',
        logo: 'https://www.eredmenyek.com/res/image/data/4KcsH9xS-bDM8X95t.png',
    },
    {
        id: 25,
        leagueId: 1,
        title: 'Chelsea',
        logo: 'https://www.eredmenyek.com/res/image/data/GMmvDEdM-2B0QucIK.png',
    },
    {
        id: 26,
        leagueId: 1,
        title: 'Crystal Palace',
        logo: 'https://www.eredmenyek.com/res/image/data/AFNlsDzS-6sMoYuga.png',
    },
    {
        id: 27,
        leagueId: 1,
        title: 'Everton',
        logo: 'https://www.eredmenyek.com/res/image/data/EwJqZUZA-Onr593up.png',
    },
    {
        id: 28,
        leagueId: 1,
        title: 'Fulham',
        logo: 'https://www.eredmenyek.com/res/image/data/naaAVOzB-fcuGVCfD.png',
    },
    {
        id: 29,
        leagueId: 1,
        title: 'Huddersfield',
        logo: 'https://www.eredmenyek.com/res/image/data/ITKcyQzB-88emtA6Q.png',
    },
    {
        id: 30,
        leagueId: 1,
        title: 'Leicester',
        logo: 'https://www.eredmenyek.com/res/image/data/Em1CYqYg-nDs49AhO.png',
    },
    {
        id: 31,
        leagueId: 1,
        title: 'Liverpool',
        logo: 'https://www.eredmenyek.com/res/image/data/vwC9RGhl-2B0QucIK.png',
    },
    {
        id: 32,
        leagueId: 1,
        title: 'Manchester City',
        logo: 'https://www.eredmenyek.com/res/image/data/UXcqj7HG-zZRehMhm.png',
    },
    {
        id: 33,
        leagueId: 1,
        title: 'Manchester United',
        logo: 'https://www.eredmenyek.com/res/image/data/nwSRlyWg-rBodzytr.png',
    },
    {
        id: 34,
        leagueId: 1,
        title: 'Newcastle',
        logo: 'https://www.eredmenyek.com/res/image/data/fojwJwZA-KYq0Zfel.png',
    },
    {
        id: 35,
        leagueId: 1,
        title: 'Southampton',
        logo: 'https://www.eredmenyek.com/res/image/data/fmA9gnyB-Ozt88U7U.png',
    },
    {
        id: 36,
        leagueId: 1,
        title: 'Tottenham',
        logo: 'https://www.eredmenyek.com/res/image/data/pjJVnSFG-bPr4YEAf.png',
    },
    {
        id: 37,
        leagueId: 1,
        title: 'Watford',
        logo: 'https://www.eredmenyek.com/res/image/data/C2N3btil-AmUVvt4h.png',
    },
    {
        id: 38,
        leagueId: 1,
        title: 'West Ham',
        logo: 'https://www.eredmenyek.com/res/image/data/Y3qglzf5-xGs8XYP0.png',
    },
    {
        id: 39,
        leagueId: 1,
        title: 'Wolves',
        logo: 'https://www.eredmenyek.com/res/image/data/Iwsrq5xS-rawILjE1.png',
    },
    {
        id: 40,
        leagueId: 2,
        title: 'Amiens',
        logo: 'https://www.eredmenyek.com/res/image/data/SS0ptyGG-C8C4WHr0.png',
    },
    {
        id: 41,
        leagueId: 2,
        title: 'Angers',
        logo: 'https://www.eredmenyek.com/res/image/data/t8LjlaWg-EorrQF3M.png',
    },
    {
        id: 42,
        leagueId: 2,
        title: 'Bordeaux',
        logo: 'https://www.eredmenyek.com/res/image/data/jXauMLBr-UH4VDsU3.png',
    },
    {
        id: 43,
        leagueId: 2,
        title: 'Caen',
        logo: 'https://www.eredmenyek.com/res/image/data/vm9V3ZyS-ddY8vYcF.png',
    },
    {
        id: 44,
        leagueId: 2,
        title: 'Dijon',
        logo: 'https://www.eredmenyek.com/res/image/data/zXp1wTyS-YHD0XcTg.png',
    },
    {
        id: 45,
        leagueId: 2,
        title: 'Guingamp',
        logo: 'https://www.eredmenyek.com/res/image/data/SQa8WRhl-6D8GTFSI.png',
    },
    {
        id: 46,
        leagueId: 2,
        title: 'Lille',
        logo: 'https://www.eredmenyek.com/res/image/data/Y91hQAzS-ruXbFOed.png',
    },
    {
        id: 47,
        leagueId: 2,
        title: 'Lyon',
        logo: 'https://www.eredmenyek.com/res/image/data/rytJfXyS-IRbzmzRB.png',
    },
    {
        id: 48,
        leagueId: 2,
        title: 'Monaco',
        logo: 'https://www.eredmenyek.com/res/image/data/8MsrhbxS-KEsKRNzC.png',
    },
    {
        id: 49,
        leagueId: 2,
        title: 'Montpellier',
        logo: 'https://www.eredmenyek.com/res/image/data/QTr0lOBr-EkChIdLk.png',
    },
    {
        id: 50,
        leagueId: 2,
        title: 'Nantes',
        logo: 'https://www.eredmenyek.com/res/image/data/xfmPY4EG-2FjS0Yaf.png',
    },
    {
        id: 51,
        leagueId: 2,
        title: 'Nice',
        logo: 'https://www.eredmenyek.com/res/image/data/boyRUvyB-jiROSmFn.png',
    },
    {
        id: 52,
        leagueId: 2,
        title: 'Nimes',
        logo: 'https://www.eredmenyek.com/res/image/data/4venbkCr-h4gLmyLR.png',
    },
    {
        id: 53,
        leagueId: 2,
        title: 'Olympique de Marseille',
        logo: 'https://www.eredmenyek.com/res/image/data/AwlBhPfM-Qk1sBuEM.png',
    },
    {
        id: 54,
        leagueId: 2,
        title: 'Paris Saint Germain',
        logo: 'https://www.eredmenyek.com/res/image/data/EskJufg5-lIDJVsTo.png',
    },
    {
        id: 55,
        leagueId: 2,
        title: 'Reims',
        logo: 'https://www.eredmenyek.com/res/image/data/zBBrdgYg-ppsUnwTt.png',
    },
    {
        id: 56,
        leagueId: 2,
        title: 'Rennes',
        logo: 'https://www.eredmenyek.com/res/image/data/dW5nRTdM-UH4VDsU3.png',
    },
    {
        id: 57,
        leagueId: 2,
        title: 'St. Etienne',
        logo: 'https://www.eredmenyek.com/res/image/data/ImkZgXYA-Qk1sBuEM.png',
    },
    {
        id: 58,
        leagueId: 2,
        title: 'Strasbourg',
        logo: 'https://www.eredmenyek.com/res/image/data/Muh3TJDa-4SOLY7oe.png',
    },
    {
        id: 59,
        leagueId: 2,
        title: 'Toulouse',
        logo: 'https://www.eredmenyek.com/res/image/data/IwvZ6Rjl-rFFjaCNe.png',
    },
    {
        id: 60,
        leagueId: 3,
        title: 'Augsburg',
        logo: 'https://www.eredmenyek.com/res/image/data/6ZUvwjgl-tGGTvWkH.png',
    },
    {
        id: 61,
        leagueId: 3,
        title: 'Bayern München',
        logo: 'https://www.eredmenyek.com/res/image/data/2XitNyyB-AylzU6N3.png',
    },
    {
        id: 62,
        leagueId: 3,
        title: 'Borussia Dortmund',
        logo: 'https://www.eredmenyek.com/res/image/data/Yiq1eU9r-dhhpTYj5.png',
    },
    {
        id: 63,
        leagueId: 3,
        title: 'Düsseldorf',
        logo: 'https://www.eredmenyek.com/res/image/data/ph4pnOh5-K6FXwj5N.png',
    },
    {
        id: 64,
        leagueId: 3,
        title: 'Frankfurt',
        logo: 'https://www.eredmenyek.com/res/image/data/f9dVVYCa-h85SGgwF.png',
    },
    {
        id: 65,
        leagueId: 3,
        title: 'Freiburg',
        logo: 'https://www.eredmenyek.com/res/image/data/ttZErLg5-jcldQWzO.png',
    },
    {
        id: 66,
        leagueId: 3,
        title: 'Hannover 96',
        logo: 'https://www.eredmenyek.com/res/image/data/IXGhyAcM-pU0JrdFp.png',
    },
    {
        id: 67,
        leagueId: 3,
        title: 'Hertha BSC',
        logo: 'https://www.eredmenyek.com/res/image/data/dQALRIjl-C6khRCLH.png',
    },
    {
        id: 68,
        leagueId: 3,
        title: 'Hoffenheim',
        logo: 'https://www.eredmenyek.com/res/image/data/I3cMF7f5-6cGmlIiN.png',
    },
    {
        id: 69,
        leagueId: 3,
        title: 'Leverkusen',
        logo: 'https://www.eredmenyek.com/res/image/data/OWpaDOYA-YFjlSh6B.png',
    },
    {
        id: 70,
        leagueId: 3,
        title: 'Mainz',
        logo: 'https://www.eredmenyek.com/res/image/data/repxf0h5-jwO5pzMu.png',
    },
    {
        id: 71,
        leagueId: 3,
        title: 'Mönchengladbach',
        logo: 'https://www.eredmenyek.com/res/image/data/rDRx1VXg-xQEMKj97.png',
    },
    {
        id: 72,
        leagueId: 3,
        title: 'Nürnberg',
        logo: 'https://www.eredmenyek.com/res/image/data/rNxwlyGG-YafhBXYt.png',
    },
    {
        id: 73,
        leagueId: 3,
        title: 'RB Leipzig',
        logo: 'https://www.eredmenyek.com/res/image/data/xrXu02Ca-t2ayNHaN.png',
    },
    {
        id: 74,
        leagueId: 3,
        title: 'Schalke 04',
        logo: 'https://www.eredmenyek.com/res/image/data/b1q14jZg-I1gtUEya.png',
    },
    {
        id: 75,
        leagueId: 3,
        title: 'VfB Stuttgart',
        logo: 'https://www.eredmenyek.com/res/image/data/x0YB6veM-Gp7OHZN8.png',
    },
    {
        id: 76,
        leagueId: 3,
        title: 'Werder Bremen',
        logo: 'https://www.eredmenyek.com/res/image/data/lEp5rDFG-C6khRCLH.png',
    },
    {
        id: 77,
        leagueId: 3,
        title: 'Wolfsburg',
        logo: 'https://www.eredmenyek.com/res/image/data/vLGOP9zB-QJro3zsK.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Alaves',
        logo: 'https://www.eredmenyek.com/res/image/data/hrI86AzS-6eawNCFf.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Athletic Bilbao',
        logo: 'https://www.eredmenyek.com/res/image/data/E9o4aVEa-xGwCks5S.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Atletico Madrid',
        logo: 'https://www.eredmenyek.com/res/image/data/CjfjIsYg-KdM6gJMF.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Barcelona',
        logo: 'https://www.eredmenyek.com/res/image/data/8dhw5vxS-trs0hqL9.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Betis',
        logo: 'https://www.eredmenyek.com/res/image/data/hvyaw5HG-lUcXmrQf.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Celta Vigo',
        logo: 'https://www.eredmenyek.com/res/image/data/GU3fItYg-bPv8jNkM.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Eibar',
        logo: 'https://www.eredmenyek.com/res/image/data/CvetxaAr-M9doLjp7.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Espanyol',
        logo: 'https://www.eredmenyek.com/res/image/data/SObn7xDr-Eq7v4whI.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Getafe',
        logo: 'https://www.eredmenyek.com/res/image/data/OjieMlGG-46ZOuRh1.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Girona',
        logo: 'https://www.eredmenyek.com/res/image/data/QJz2LlBr-EHKRdX9e.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Huesca',
        logo: 'https://www.eredmenyek.com/res/image/data/UwzkXAxS-jq1jgydj.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Leganes',
        logo: 'https://www.eredmenyek.com/res/image/data/htTcG0il-IosBD5s5.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Levante',
        logo: 'https://www.eredmenyek.com/res/image/data/25Tx45il-jHKOVbXE.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Rayo Vallecano',
        logo: 'https://www.eredmenyek.com/res/image/data/jqaha0f5-SCAy65MC.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Real Madrid',
        logo: 'https://www.eredmenyek.com/res/image/data/A7kHoxZA-2irdgP53.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Real Sociedad',
        logo: 'https://www.eredmenyek.com/res/image/data/r7gpvheM-rkrFLaiH.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Sevilla',
        logo: 'https://www.eredmenyek.com/res/image/data/G2BgO5Ar-nPyHsmOl.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Valencia',
        logo: 'https://www.eredmenyek.com/res/image/data/O2FpIYg5-KYu4i3zG.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Valladolid',
        logo: 'https://www.eredmenyek.com/res/image/data/8SnqB3EG-xGwCks5S.png',
    },
    {
        id: 78,
        leagueId: 4,
        title: 'Villarreal',
        logo: 'https://www.eredmenyek.com/res/image/data/65Z85Uh5-noNk3ENb.png',
    }
];